# Generated by Django 5.0.6 on 2024-05-18 20:20

import django.db.models.deletion
from django.db import migrations, models

def populate_dictionary_data(apps, schema_editor):
    PeerGroup = apps.get_model('mainapp', 'PeerGroup')
    peer_group = PeerGroup(name = 'EveryOne', description = 'All peers in the system')
    peer_group.save()

    Target = apps.get_model('mainapp', 'Target')
    target = Target(name = 'Internet', description = 'Mmmmm....Internet....')
    target.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('disabled', models.BooleanField(null=True)),
                ('allow_modify_self', models.BooleanField(null=True)),
                ('allow_modify_peers', models.BooleanField(null=True)),
                ('allow_modify_targets', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('disabled', models.BooleanField(null=True)),
                ('ip_address', models.IntegerField(max_length=255, null=True)),
                ('port', models.IntegerField(null=True)),
                ('public_key', models.CharField(max_length=255, null=True)),
                ('private_key', models.CharField(max_length=255, null=True)),
                ('peer_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.peergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('disabled', models.BooleanField(null=True)),
                ('ip_address', models.CharField(max_length=255, null=True)),
                ('port', models.IntegerField(null=True)),
                ('allow_modify_self', models.BooleanField(null=True)),
                ('allow_modify_peergroups', models.BooleanField(null=True)),
                ('peer_groups', models.ManyToManyField(to='mainapp.peergroup')),
            ],
        ),
        migrations.AddField(
            model_name='peergroup',
            name='targets',
            field=models.ManyToManyField(to='mainapp.target'),
        ),
        migrations.RunPython(populate_dictionary_data),
    ]
