# Generated by Django 5.0.6 on 2024-05-18 21:48

from django.db import migrations, models

def populate_dictionary_data(apps, schema_editor):
    PeerGroup = apps.get_model('mainapp', 'PeerGroup')
    peer_group = PeerGroup(name = 'EveryOne', description = 'All peers in the system',
                           allow_modify_self = False,
                           allow_modify_peers = False,
                           allow_modify_targets = True,)
    peer_group.save()

    Target = apps.get_model('mainapp', 'Target')
    target = Target(name = 'Internet', description = 'Mmmmm....Internet....',
                    allow_modify_self = False,
                    allow_modify_peer_groups = True,)
    target.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('disabled', models.BooleanField(null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('private_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('disabled', models.BooleanField(null=True)),
                ('allow_modify_self', models.BooleanField(null=True)),
                ('allow_modify_peers', models.BooleanField(null=True)),
                ('allow_modify_targets', models.BooleanField(null=True)),
                ('peers', models.ManyToManyField(blank=True, to='mainapp.peer')),
            ],
        ),
        migrations.AddField(
            model_name='peer',
            name='peer_groups',
            field=models.ManyToManyField(blank=True, to='mainapp.peergroup'),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('disabled', models.BooleanField(null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('allow_modify_self', models.BooleanField(null=True)),
                ('allow_modify_peer_groups', models.BooleanField(null=True)),
                ('peer_groups', models.ManyToManyField(blank=True, to='mainapp.peergroup')),
            ],
        ),
        migrations.AddField(
            model_name='peergroup',
            name='targets',
            field=models.ManyToManyField(blank=True, to='mainapp.target'),
        ),
        migrations.RunPython(populate_dictionary_data),
    ]
