# Generated by Django 5.0.6 on 2024-05-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peergroup',
            name='targets',
            field=models.ManyToManyField(blank=True, to='mainapp.target'),
        ),
        migrations.AlterField(
            model_name='target',
            name='peer_groups',
            field=models.ManyToManyField(blank=True, to='mainapp.peergroup'),
        ),
    ]
