# Generated by Django 5.0.6 on 2024-05-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='disabled',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='peergroup',
            name='allow_modify_peers',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='peergroup',
            name='allow_modify_self',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='peergroup',
            name='allow_modify_targets',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='peergroup',
            name='disabled',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='allow_modify_peer_groups',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='allow_modify_self',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='disabled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
