# Generated by Django 5.0.6 on 2024-05-18 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_peer_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='peer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.peergroup'),
        ),
    ]
