# Generated by Django 5.0.6 on 2024-05-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_peer_peer_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='peer_group',
        ),
        migrations.AddField(
            model_name='peer',
            name='peer_groups',
            field=models.ManyToManyField(blank=True, to='mainapp.peergroup'),
        ),
    ]
