# Generated by Django 5.0.6 on 2024-05-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_peer_peer_group_peer_peer_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='peer',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
