# Generated by Django 5.0.6 on 2024-05-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_peer_ip_address_alter_peer_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='peer',
            name='public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
