# Generated by Django 5.0.6 on 2024-05-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_peer_private_key_alter_peer_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='peergroup',
            name='peers',
            field=models.ManyToManyField(blank=True, to='mainapp.peer'),
        ),
    ]
