#!/bin/bash

BASE_DIR="$(dirname "$(readlink -f "${BASH_SOURCE}")")"

source ${BASE_DIR}/build-dev

docker run -it --rm \
  -v "${BASE_DIR}":/wg-ui-plus \
  -v "${BASE_DIR}/app":/app \
  -v "${HOME}/.gitconfig":/home/pi/.gitconfig:ro \
  -v /tmp:/tmp \
  --name wg-ui-dev-ng \
  wg-ui-plus-dev /wg-ui-plus/scripts/ng-build.sh
