#!/bin/bash

BASE_DIR="$(dirname "$(readlink -f "${BASH_SOURCE}")")"

source ${BASE_DIR}/build-dev


runing_container=`docker container ls | grep ${CONTAINER_DEV_APP}`

if [ "${runing_container}" = "" ]
then
    echo "First run the dep-app container."
else
    docker exec -it ${CONTAINER_DEV_APP} bash
fi
