#!/bin/bash

IMAGE_NAME='test_wguiplus'
IMAGE_LATEST="${IMAGE_NAME}:latest"

build_image () {
	echo "[INFO] Builing image ${IMAGE_LATEST}"
	# Using '--no-cache' here because we want to ensure the image is totally rebuilt
	docker build --tag "${IMAGE_LATEST}" --no-cache .
}

LOCAL_IMAGE_LISTING_COUNT=$(docker image ls "${IMAGE_NAME}:latest" | tail +2 | wc -l)

if [[ "${LOCAL_IMAGE_LISTING_COUNT}" -eq 0 ]]; then
	echo '[INFO] Local image no yet built'
	build_image
elif [[ "${LOCAL_IMAGE_LISTING_COUNT}" -eq 1 ]]; then
	echo '[INFO] Local image already existed'
else
	echo '[ERROR] More than one image exists local, no idea what to do now!'
fi

CONTAINER='wguiplus_upgrade_test'
echo '[INFO] Starting container to check for upgrades'
SIMULATED_UPGRADE_RESULTS=$(docker run -it --rm --name "${CONTAINER}" "${IMAGE_LATEST}" apk -U upgrade --simulate)
UPGRADEABLE_PACKAGES=$(echo ${SIMULATED_UPGRADE_RESULTS} | grep --only-matching 'Upgrading' | wc -l)
if [[ "${UPGRADEABLE_PACKAGES}" -eq 0 ]]; then
	echo '[INFO] No pacakges detected as upgradable'
else
	echo "[INFO] Detected ${UPGRADEABLE_PACKAGES} pacakges that can be upgraded"
	build_image
fi
