# Generated by Django 5.0.6 on 2024-05-20 13:33

from django.db import migrations, models

def populate_dictionary_data(apps, schema_editor):
    PeerGroup = apps.get_model('api_app', 'PeerGroup')
    peer_group = PeerGroup(name = 'EveryOne', description = 'All peers in the system',
                           allow_modify_self = False,
                           allow_modify_peers = False,
                           allow_modify_targets = True,)
    peer_group.save()

    Target = apps.get_model('api_app', 'Target')
    target = Target(name = 'Internet', description = 'Mmmmm....Internet....',
                    allow_modify_self = False,
                    allow_modify_peer_groups = True,)
    target.save()

    ServerConfiguration = apps.get_model('api_app', 'ServerConfiguration')
    serverConfiguration = ServerConfiguration(host_name_external = 'myvpn.duckdns.org',
                    ip_address = '192.168.2.1/24',
                    port_external = 1196,
                    port_internal = '51820',
                    wireguard_config_path = '/config/wireguard/wg0.conf',
                    script_path_post_down = '/config/wireguard/scripts/post-up.sh',
                    script_path_post_up = '/config/wireguard/scripts/post-down.sh',
                    public_key = 'public key',
                    private_key = 'private key',
                    peer_default_port = 1196)
    serverConfiguration.save()



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('disabled', models.BooleanField(default=False, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('private_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('host_name_external', models.CharField(max_length=255)),
                ('port_external', models.IntegerField()),
                ('port_internal', models.IntegerField()),
                ('wireguard_config_path', models.CharField(max_length=255)),
                ('script_path_post_down', models.CharField(max_length=255)),
                ('script_path_post_up', models.CharField(max_length=255)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('private_key', models.CharField(blank=True, max_length=255, null=True)),
                ('peer_default_port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PeerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('disabled', models.BooleanField(default=False, null=True)),
                ('allow_modify_self', models.BooleanField(default=True, null=True)),
                ('allow_modify_peers', models.BooleanField(default=True, null=True)),
                ('allow_modify_targets', models.BooleanField(default=True, null=True)),
                ('peers', models.ManyToManyField(blank=True, to='api_app.peer')),
            ],
        ),
        migrations.AddField(
            model_name='peer',
            name='peer_groups',
            field=models.ManyToManyField(blank=True, to='api_app.peergroup'),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('disabled', models.BooleanField(default=False, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('allow_modify_self', models.BooleanField(default=True, null=True)),
                ('allow_modify_peer_groups', models.BooleanField(default=True, null=True)),
                ('peer_groups', models.ManyToManyField(blank=True, to='api_app.peergroup')),
            ],
        ),
        migrations.AddField(
            model_name='peergroup',
            name='targets',
            field=models.ManyToManyField(blank=True, to='api_app.target'),
        ),
        migrations.RunPython(populate_dictionary_data),
    ]
