# Generated by Django 5.0.6 on 2024-05-22 21:08

import api_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverconfiguration',
            name='upstream_dns_ip_address',
            field=models.CharField(max_length=255, validators=[api_app.models.is_single_address]),
        ),
    ]
