# Generated by Django 5.0.6 on 2024-05-27 21:00

from django.db import migrations
from ..db_seed import populate_dictionary_data

class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_dictionary_data)
    ]
