# Generated by Django 5.0.6 on 2024-06-16 11:54

import api_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20240526_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='ip_address',
            field=models.CharField(max_length=255, validators=[api_app.models.validator_is_valid_target_ip_address]),
        ),
    ]
