# Generated by Django 5.0.6 on 2024-05-23 23:57

import api_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_serverconfiguration_upstream_dns_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfiguration',
            name='local_networks',
            field=models.CharField(blank=True, max_length=512, null=True, validators=[api_app.models.are_network_addresses]),
        ),
    ]
