# Generated by Django 5.0.6 on 2024-05-30 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20240526_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='peer_groups',
        ),
        migrations.RemoveField(
            model_name='peergroup',
            name='targets',
        ),
    ]
