# Generated by Django 5.1.3 on 2024-11-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_target_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfiguration',
            name='allow_check_updates',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
