# Generated by Django 5.0.6 on 2024-06-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_target_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfiguration',
            name='use_ping_to_check_connectivity',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
