# Generated by Django 5.1.3 on 2024-11-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_serverconfiguration_allow_check_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='email_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
