# Generated by Django 5.1.4 on 2024-12-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_peer_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfiguration',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
