# Generated by Django 5.1.4 on 2024-12-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_serverconfiguration_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfiguration',
            name='strict_allowed_ips_in_peer_config',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
