# Generated by Django 5.1.4 on 2024-12-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_alter_serverconfiguration_last_changed_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfiguration',
            name='wireguard_config_change_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
