# Generated by Django 5.1.4 on 2024-12-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_serverconfiguration_wireguard_config_change_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverconfiguration',
            name='last_changed_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
