# Generated by Django 5.1.7 on 2025-03-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_alter_serverconfiguration_last_changed_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverconfiguration',
            name='wireguard_config_change_datetime',
        ),
    ]
