# Generated by Django 5.1.7 on 2025-03-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_remove_serverconfiguration_wireguard_config_change_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverconfiguration',
            name='last_changed_datetime',
            field=models.DateTimeField(),
        ),
    ]
