# Generated by Django 5.1.15 on 2026-08-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0013_serverconfiguration_mcp'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfiguration',
            name='email_default_from_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serverconfiguration',
            name='email_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serverconfiguration',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serverconfiguration',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serverconfiguration',
            name='email_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serverconfiguration',
            name='email_use_ssl',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='serverconfiguration',
            name='email_use_tls',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
