name: Clean old docker images published to GH Packages

on:
  - workflow_call
  - workflow_dispatch

jobs:
  delete:
    runs-on: ubuntu-latest
    name: Remove except latest few
    permissions: write-all
    steps:
      - name: Set ENV variables
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
      - name: Delete packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.REPO_NAME }}
          package-type: 'container'
          min-versions-to-keep: 5

