name: Docker Image CI - Pre-built base images

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 6 * * *" # everyday at 6 AM

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Show context values
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event_path: ${{ github.event_path }}"
          echo "github.ref_name  : ${{ github.ref_name }}"
          echo "github.ref       : ${{ github.ref }}"

  build-base-dev:
    needs: init
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image - base-dev
        id: push_gh_hosted_base_dev
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: false
          context: .
          file: base.Dockerfile
          target: base-dev
          build-args: |
            APP_VERSION=base-dev
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-dev

  build-base-live:
    needs: init
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image - base-live
        id: push_gh_hosted_base_live
        uses: docker/build-push-action@v6
        with:
          context: .
          file: base.Dockerfile
          target: base-live
          build-args: |
            APP_VERSION=base-live
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-live
          provenance: false

  clean-untagged-images:
    needs:
      - build-base-dev
      - build-base-live
    permissions: write-all
    secrets: inherit
    uses:
      ./.github/workflows/clean-ghcr-packages-untagged.yml