name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - feature/ui-fixes
  pull_request:
    branches:
      - develop
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        runner: ["ubuntu-latest", "self-hosted"]
    runs-on: ${{ matrix.runner }}
    permissions: write-all
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ matrix.runner }}-${{ github.ref_name }}-${{ github.sha }}

    - name: Build and push Docker image (without cache)
      if: matrix.runner == 'ubuntu-latest'
      id: push_no_cache
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: false

    - name: Build and push Docker image (with cache)
      if: matrix.runner == 'self-hosted'
      id: push_with_cache
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: false
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      if: matrix.runner == 'self-hosted'
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache      
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896

  create-multiarch-image:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash
    permissions: write-all
    steps:
      - name: Generate timestamp for docker image tags
        id: gen_timestamp
        run: |
          echo "timestamp=$(date +%Y-%m-%d-%H-%M)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create multiarch manifests (published release only)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker buildx imagetools create \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-${{ github.ref_name }} \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:ubuntu-latest-${{ github.ref_name }}-${{ github.sha }} \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:self-hosted-${{ github.ref_name }}-${{ github.sha }}

      - name: Create multiarch manifests (non-master branch)
        if: !startsWith(github.ref, 'refs/tags/v')
        run: |
          docker buildx imagetools create \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ steps.gen_timestamp.outputs.timestamp }} \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }} \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:ubuntu-latest-${{ github.ref_name }}-${{ github.sha }} \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:self-hosted-${{ github.ref_name }}-${{ github.sha }}

  clean_old_packages:
    needs: create-multiarch-image
    permissions: write-all
    uses: ./.github/workflows/clean-up-oldpackages.yml

