name: Docker Image CI

on:
  push:
    branches:
      - master
      - develop
      - feature/ui-fixes
  pull_request:
    branches:
      - master
      - develop
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: dev

jobs:
  build:
    strategy:
      matrix:
        runner: ["ubuntu-latest", "self-hosted"]
    runs-on: ${{ matrix.runner }}
    permissions: write-all
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ env.IMAGE_TAG }}-${{ matrix.runner }}
          type=raw,value={{date 'YYYY-MM-DD-HH-mm'}}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: false
          #        cache-from: type=gha
          #        cache-to: type=gha,mode=max
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache      
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896

  create-multiarch-image:
    runs-on: ubuntu-22.04
    needs: build
    defaults:
      run:
        shell: bash
    permissions: write-all
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create multiarch manifests
        run: |
          docker buildx imagetools create -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-ubuntu-latest \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-self-hosted

  remove-temporary-images:
    needs: create-multiarch-image
    runs-on: ubuntu-latest
    name: Remove temporary images
    permissions: write-all
    steps:
      - name: Set ENV variables
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
      - name: Delete packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.REPO_NAME }}
          package-type: 'container'
          package-version-ids: 'dev-ubuntu-latest,dev-self-hosted'

  clean_old_packages:
    needs: create-multiarch-image
    permissions: write-all
    uses: ./.github/workflows/clean-up-oldpackages.yml

