name: Delete GHCR Containers by Regex Pattern

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}
  REGEX_PATTERN: "^(self-hosted|ubuntu-latest)-.*"

jobs:
  delete-containers:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:

      - name: List and Delete Containers
        run: |
          # Define the regex pattern
          for i in {1..3}
          do
            # Get the list of container tags
            gh api -H "Accept: application/vnd.github.v3+json" "/user/packages/container/wg-ui-plus/versions?page=${1}&per_page=100" \
            | jq -r '.[] | select(.metadata.container.tags[] | test(env.REGEX_PATTERN)) | .id' \
            | while read -r version_id; do
                echo "Deleting container version: $version_id"
                echo "gh api --method DELETE -H \"Accept: application/vnd.github.v3+json\" /user/packages/container/wg-ui-plus/versions/\"$version_id\""
                gh api --method DELETE -H "Accept: application/vnd.github.v3+json" /user/packages/container/wg-ui-plus/versions/"$version_id"
              done
          done
