name: Delete GHCR Containers by Regex Pattern

on:
  workflow_dispatch:

env:
  REGEX_PATTERN: '^your-regex-pattern$'
  GH_TOKEN: ${{ github.token }}
  PACKAGE_NAME: wg-ui-plus

jobs:
  delete-containers:
    runs-on: ubuntu-latest
    steps:

      - name: List and Delete Containers
        run: |
          # Define the regex pattern
          REGEX_PATTERN="^your-regex-pattern$"
          
          # Get the list of container tags
          gh api -H "Accept: application/vnd.github.v3+json" /user/packages/container/${{ PACKAGE_NAME }}/versions \
          | jq -r '.[] | select(.metadata.container.tags[] | test(env.REGEX_PATTERN)) | .id' \
          | while read -r version_id; do
              echo "Deleting container version: $version_id"
              echo "gh api --method DELETE -H \"Accept: application/vnd.github.v3+json\" /user/packages/container/${{ PACKAGE_NAME }}/versions/\"$version_id\""
            done
