name: Delete GHCR Containers by Regex Pattern

on:
  workflow_dispatch:

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  delete-containers:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: List packages
      run: |
        gh api -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /user/packages?package_type=container
