name: Delete GHCR Containers by Regex Pattern

on:
  workflow_dispatch:

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  delete-containers:
    runs-on: ubuntu-latest

    steps:
      - name: List packages version
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
             /user/packages/container/wg-ui-plus/versions
      - name: List packages version
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
             /user/packages/container
